### ISSUE TITLE
How to embed image?

### ISSUE THREAD

**Issue by ooker777** [denoland/deno-gfm#103]
On `static` folder I have a `cover.png` image. In `routes/index.tsx` I have:
```tsx
import { CSS, render } from "https://deno.land/x/gfm/mod.ts";

const body = render(`# Hello, world!
![](../static/cover.png)
![](./static/cover.png)
![](/static/cover.png)
![](static/cover.png)
`);

export default function a() {
    return <main dangerouslySetInnerHTML={{ __html: body }}>
    {body}
    </main>
} 
```
There is no image. Why is that?

**Comment by deer** [comment]
You asked the same question in the SaaSKit discord a few days ago but did not respond to either of the two people who answered you.

All of those are valid markdown, in the sense that they produce an `img` tag. In the future, please provide more details. Although it's now clear to me that you're using Fresh. The [static files](https://fresh.deno.dev/docs/concepts/static-files) documentation says:
> Fresh automatically serves static assets placed in a static/ directory in the project root.

So if you want to access your `/static/cover.png` file, the request (in your browser or wherever) should be to `http://localhost:8000/cover.png`. Then your markdown needs to be something like:
```md
![you should always provide alt text](/cover.png)
```

**Comment by ooker777** [comment]
Thanks. At the time of testing I was surprised that this simple feature didn't work correctly, so my confidence in believing that this is a bug not a lack of my knowledge raised... I have no idea what I was thinking...

**Comment by deer** [comment]
Sorry, it's not super clear whether this solved your problem. If so, please close the issue. If not, I'm happy to debug further.
