### ISSUE TITLE
Allow task lists

### ISSUE THREAD

**Issue by ooker777** [denoland/deno-gfm#104]
In `routes/index.tsx`:
```tsx
import { CSS, render } from "https://deno.land/x/gfm/mod.ts";

const body = render(`# Hello, world!
- Normal list
- [x] #739
- [ ] https://github.com/octo-org/octo-repo/issues/740
- [ ] Add delight to the experience when all tasks are complete :tada:
`);

export default function a() {
    return <main dangerouslySetInnerHTML={{ __html: body }}>
    {body}
    </main>
} 
```
I expect it to create correct check boxes, not regular list.

[About task lists - GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#creating-task-lists "About task lists - GitHub Docs")

**Comment by deer** [comment]
Thanks, this is a pretty big issue. I'm surprised it hasn't been reported before. I've opened a PR to fix it.
