### ISSUE TITLE
Whitelist various html5 tags

### ISSUE THREAD

**Issue by RickCogley** [denoland/deno-gfm#11]
I'd like to see these html5 tags whitelisted, so we can target them in `gfm.css.ts`. 

```
<cite>, <mark>, <acronym>, <abbr>, <address>, <ins>, <del>, <details> and <summary, <meter>
``` 

The `<meter>` tag is good for indicating how much of something, so you could show your skill level in a topic, in a resume for instance. 

```
X Skill: <meter optimum="40" high="80" max="100" value="20">85%</meter>
```

A highlight class in a div is already whitelisted, so, you can do like this in `gfm.css.ts`: 

```
.markdown-body .highlight {
  background: azure;
}
```

And add this to your markdown file for a "poor man's callout": 

```
<div class="highlight"><strong>Note:</strong> Some text like a warning or tip, you want to emphasize... </div>
```

**Comment by RickCogley** [comment]
I was thinking I could set an id on div or span, but that's not whitelisted either. The ability to do so should enable us to add css for different color highlights. 

I'm thinking about making "tip", "warning", "info" highlighted blocks with different highlight colors, and so on.

**Comment by lino-levan** [comment]
Given that we now have `disableHTMLSanitization`, is this still valuable (especially since GitHub doesn't enable these by default iirc)?
