### ISSUE TITLE
JSR and client side rendering with gfm

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno-gfm#119]
Previously on deno.land/x/gfm versions it was possible to incorporate gfm into an interactive island and do client side rendering of dynamic in browser markdown.  Since migration to JSR, trying to incorporate gfm client side causes complaints about things like `node:buffer` and other items trying to be incorporated into the bundle, causing the client side island to fail to load.

I am not sure actually who to blame, be it JSR, Fresh or gfm, but I am going to point the finger first at gfm since going back to `https://deno.land/x/gfm@0.6.0` appears to fix things.

**Comment by Mrashes** [comment]
Looks like this was fixed based on the mentioned build - @kitsonk are you still seeing this issue?

**Comment by kitsonk** [comment]
Yes, current versions of gfm do not appear to have this problem.
