### ISSUE TITLE
Consider "shortcuts" for use in markdown files

### ISSUE THREAD

**Issue by RickCogley** [denoland/deno-gfm#12]
I notice that @lucacasonato's [freshworkshop](https://github.com/lucacasonato/freshworkshop/blob/main/routes/blog/%5Bid%5D.tsx) and [the fresh docs](https://github.com/denoland/fresh/blob/main/www/routes/docs/%5B...slug%5D.tsx) both use deno-gfm. 

I see that fresh docs have a custom `gfm.css.ts` file for customizing styles, so we get a bit of customizability working with the tags inside the rendered markdown area. 

Some markdown engines, especially SSG's in particular, let you define "shortcuts" that are then parsed into something that has a bit complicated HTML structure like a "callout" which might be structured as such, but its html defined elsewhere:  

```
{% callout title="Tip!" %}
This is the body of the tip with a [markdown link](/some/url/path).
{% /callout %}
```

Does this kind of thing exist in gfm? If not, it would be a great addition.

**Comment by RickCogley** [comment]
Please let me know, is this sort of thing is not possible due to how Fresh works?

**Comment by lino-levan** [comment]
This is a cool concept but I don't know if it makes sense to integrate with **GitHub flavored** markdown. I'd love to see this but as a third party module on top of what this already offers.

**Comment by hashrock** [comment]
It might be out of scope for deno-gfm, maybe we could handle this before or after deno-gfm processing step. Or maybe do it in Custom Elements?

**Comment by hashrock** [comment]
Let me close this issue for now,but feel free to reopen if you find other useful use cases.
