### ISSUE TITLE
Inquiry about the release date for @deno/gfm 0.10.0

### ISSUE THREAD

**Issue by dominikj111** [denoland/deno-gfm#131]
Hi,
I noticed that the latest release is version 0.9.0, and I was wondering if there is an estimated release date for version 0.10.0.

I'm encountering with this issue https://github.com/denoland/saaskit/issues/689 and the 0.10.0 version will solve it.

**Comment by crowlKats** [comment]
@dominikj111 apologies about it; thought the release process worked, but missed a step. 10 is now released

**Comment by dominikj111** [comment]
Also @crowlKats I'm wondering if you can update this https://deno.land/x/gfm ... there version 0.6.0 marked as latest.

**Comment by crowlKats** [comment]
@dominikj111 sadly we cannot publish to /x/ since nowadays we use an importmap to define the dependencies, which is not something that is possible on /x/
