### ISSUE TITLE
Can't import latest version?

### ISSUE THREAD

**Issue by hirohitokato** [denoland/deno-gfm#132]
When I use gfm on the deno 2, the error occurs and it does not work.

## Reproducible code

```ts
import { CSS, render } from "https://deno.land/x/gfm/mod.ts";
const body = render("");
```
### Expected result

works without error.

### Actual result

Dumps following error.

```
error: Import assertions are deprecated. Use `with` keyword, instead of 'assert' keyword.

import emojis from "./all.json" assert { type: "json" };

  at https://deno.land/x/emoji@0.3.0/emoji.ts:2:1
```

## Environment

```sh
> deno --version
deno 2.0.6 (stable, release, x86_64-pc-windows-msvc)
v8 12.9.202.13-rusty
typescript 5.6.2
```

## Other information

When I saw the contents of `https://deno.land/x/gfm`, The latest version shows still 0.6.0, even if the actual latest version is 0.10.0.

**Comment by crowlKats** [comment]
@hirohitokato we don't recommend using the /x/ package anymore, but rather the JSR package: https://jsr.io/@deno/gfm
