### ISSUE TITLE
Add support for links that reference the working directory with a baseUrl

### ISSUE THREAD

**Issue by M4rteaga** [denoland/deno-gfm#14]
There are cases where a link uses dot notation, referencing the working directory.

 eg: 
```javascript
const link = './useHead.mjs'
const baseUrl = 'https://deno.land/x/ruck@v7.0.0'
```
In this case with the current link treatment, the result of the link will be:
```javascript
const linkAfterGfm =  'https://deno.land/x/useHead.mjs'
```
generating issues as shown in [Relative URLs in readme markdown starting with `./` render broken · Issue #2060 · denoland/dotland](https://github.com/denoland/dotland/issues/2060)

**Comment by hashrock** [comment]
I'll close this due to related PR was closed. If the problem has not been resolved yet, please re-open it.
