### ISSUE TITLE
Rewrite URL when relative path is used in img element

### ISSUE THREAD

**Issue by hashrock** [denoland/deno-gfm#21]
When using images in Markdown format, relative paths are rewritten to absolute paths based on basePath. But this does not happen with the img element.

```mdx
// OK
![Logo](./logo.png)

// NG
<img src="./logo.png" />
```

GitHub's markdown rendering rewrites `src` in img elements, so this needs to be implemented if the behavior is to be the same.

Related:

https://github.com/denoland/fresh/issues/861
https://github.com/denoland/fresh/pull/862

**Comment by codesculpture** [comment]
Its been 3 days buddy they are not responding and its nice to see another person point this😄

**Comment by codesculpture** [comment]
It was already PRed here but not yet merged, here the PR  #18

**Comment by hashrock** [comment]
This Issue was happening for a different reason than #18, but it seems not reproducing any more. closed for now
