### ISSUE TITLE
Strikethrough using tilde not working

### ISSUE THREAD

**Issue by vwkd** [denoland/deno-gfm#23]
Strikethrough using single tilde `~` or double tilde `~~` don't work.

## Example

```js
import { render } from "https://deno.land/x/gfm/mod.ts";

console.log(render("hello ~world~"));
console.log(render("hello ~~world~~"));
```

## Expected Output

```html
<p>hello <del>world</del></p>
```

## Actual Output

```html
<p>hello world</p>
```

## Notes

marked.js gives the correct output.

https://marked.js.org/demo/?outputType=html&text=hello%20~world~%0A%0Ahello%20~~world~~&version=4.0.12

**Comment by LeoDog896** [comment]
Should be fixed in #25
