### ISSUE TITLE
Consider supporting inline markdown

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno-gfm#27]
Inline markdown could be useful for lightweight markup on blog post titles, and it could be implemented easily with Marked's `parseInline` function.

**Comment by lino-levan** [comment]
Could you elaborate on what you mean by "inline markdown"? I can't seem to find a consistent definition on the internet.

**Comment by andreubotella** [comment]
By "inline markdown" I meant allowing only a single Markdown paragraph in the source, and having the rendered HTML only have inline HTML content (no `<p>`). My use case is to use this to allow inline markup in blog titles, such that you can just do `<h1>${renderInline(post.title)}</h1>`.

This could be done as a post-processing step on `render(post.title)`, but marked (the Markdown parser/compiler deno-gfm uses under the hood) already supports inline markdown, so adding support for it is trivial.
