### ISSUE TITLE
syntax highlighting not working for "ts" ("typescript")

### ISSUE THREAD

**Issue by andykais** [denoland/deno-gfm#29]
https://deno.land/x/torm@1.0.2 (the code block tag is "`ts`")
<img width="833" alt="Screen Shot 2023-01-06 at 10 05 33 AM" src="https://user-images.githubusercontent.com/6627147/211039353-fba56668-4cec-4b6e-9d37-aea6f937e4c1.png">

which renders properly on github https://github.com/andykais/
<img width="909" alt="Screen Shot 2023-01-06 at 10 07 57 AM" src="https://user-images.githubusercontent.com/6627147/211039563-8e419bfe-5e21-43f1-b482-c27f69c419fb.png">
torm

**Comment by andykais** [comment]
I think I found the solution, in deps.ts you need to load typescript as a language (probably a more robust solution would be to dynamically load the languages depending on what is demanded of the rendered). That, or come up with a hard list of supported code tags. Im not sure how exactly this renderer is ran in production though, so thats probably a better question for you guys to answer.


```ts
// deps.ts
import Prism from "npm:prismjs@1.29.0"
import loadLanguages from 'npm:prismjs@1.29.0/components/index.js'
loadLanguages(['typescript']);

export { Prism }
```

unfortunately my job makes it difficult to contribute back to existing open source libraries, otherwise I would open a PR 😞

**Comment by lino-levan** [comment]
In [the README](https://github.com/denoland/deno-gfm#extensibility) it states:
> By default syntax highlighting for JavaScript, Markdown, and HTML is included. You can include more languages importing them.

Typescript is not on that list (even if I personally think it should be).

Unless you are suggesting to auto-load languages depending on the code blocks that deno-gfm encounters, this isn't an actionable issue.

**Comment by lino-levan** [comment]
After reading https://github.com/denoland/dotland/issues/2653, this issue becomes more clear. To summarize: sometimes language support doesn't work even if that language support is explicitly loaded.

see: https://deno.land/x/torm@1.0.2 for an example.

**Comment by tmchein** [comment]
Do you still have this issue? I checked your library and it seems to be highlighted.

**Comment by lino-levan** [comment]
I think https://github.com/denoland/dotland/pull/2659 fixed the downstream issue. I don't think there was an issue with upstream (this repo).
