### ISSUE TITLE
broken in `fresh` due to removal of `esm.sh` pin of `sanitize-html`

### ISSUE THREAD

**Issue by hyp3rflow** [denoland/deno-gfm#3]
`sanitize-html` without pin uses deno_std@0.128.0 which contains top-level await module (https://deno.land/std@0.128.0/node/internal/util/debuglog.ts#L109).
With latest fresh(https://github.com/lucacasonato/fresh/commit/64e6a7b43d6dd24964be85906f764dbe1b6b3924) and this fixed version of esbuild_deno_loader (https://github.com/lucacasonato/esbuild_deno_loader/pull/5), everything works fine.
<img width="526" alt="image" src="https://user-images.githubusercontent.com/49385012/160081560-b15e32aa-f8cb-44fb-8c71-9c1d934672f3.png">

**Comment by crowlKats** [comment]
Closing as everything works now
