### ISSUE TITLE
Slow load times

### ISSUE THREAD

**Issue by KorigamiK** [denoland/deno-gfm#47]
Upon every run of any script that uses gfm the following 2 files are being downloaded.
This is especially annoying when reloading the scripts and causes the projects hosted on deno.dev to have slow startup times. 

```bash
test/deno-gfm git:(main) ▶ deno task dev
Task dev deno run -A --unstable --watch --no-check ./example/main.ts
Watcher Process started.
Download https://esm.sh/v106/@types/katex@0.16.0/dist/katex.mjs~.d.ts (0/2)
```

What causes this unnecessary types downloading and how can it be avoided?

**Comment by hashrock** [comment]
strange, this is not happen to me with deno 1.31.1 (release, x86_64-pc-windows-msvc)

Will it stop working if I run this?

> deno run -A --unstable --watch --no-check --cached-only ./example/main.ts

**Comment by ayame113** [comment]
I've run into this issue as well, but running with the `--reload` flag fixed it.
(Perhaps this is a bug in esm.sh that has been fixed recently.)

**Comment by KorigamiK** [comment]
> strange, this is not happen to me with deno 1.31.1 (release, x86_64-pc-windows-msvc)
> 
> Will it stop working if you run this?
> 
> > deno run -A --unstable --watch --no-check --cached-only ./example/main.ts

Yes! This also seem to solve the issue.


> I've run into this issue as well, but running with the `--reload` flag fixed it. (Perhaps this is a bug in esm.sh that has been fixed recently.)

Yes, this seems to be the cause of the issue. 

In fact, running with the `--reload` flag seem to solve this issue on other projects as well, albeit I was required to delete the `deno.lock` file before I could run the dev commands.

Which makes me wonder, is is advisable to upload the `deno.lock` files when deploying to deno? Since, `package-lock.json` files should be commited to the codebases.

**Comment by hashrock** [comment]
I don't recommend committing `deno.lock` in a project that uses `esm.sh`.

I assume that deno.lock assumes that the resource that the URL points to is immutable, and if the resource is rewritten over time, it will stop with an error.

There should be a URL parameter to make esm.sh immutable too, but it doesn't seem to be always working.

Maybe this situation will change when the `deno.lock` spec changes or an immutable `esm.sh` replacement comes out. I don't recommend committing deno.lock on the front end right now.

**Comment by KorigamiK** [comment]
Got it. Thanks 😊
