### ISSUE TITLE
Write more tests

### ISSUE THREAD

**Issue by hashrock** [denoland/deno-gfm#50]
PR welcome!

- [x] transformMedia
- [x] allowIframes
- [x] disableHtmlSanitization
- [x] code block
- [ ] browser tests - mainly CSS

I'm not looking to get coverage to 100%, but I'd like to get it to over 80%. you can check it by `deno task coverage` and `deno coverage ./cov_profile`

**Comment by i8abyte** [comment]
Hi, can I please work on this issue?

**Comment by hashrock** [comment]
Of course!

**Comment by i8abyte** [comment]
Can you assign the issue to me?

**Comment by deer** [comment]
@hashrock, looks like you added `disableHtmlSanitization` tests in https://github.com/denoland/deno-gfm/pull/62. So all we need now are the browser tests. Can you please elaborate on what you're looking for?

**Comment by hashrock** [comment]
Thanks for the catch!

The browser test was mentioned here:

https://github.com/denoland/deno-gfm/pull/49#issuecomment-1462381864

However, if the CSS is the same, the rendering result should not change, so we might not need to do browser testing here. or we might need a VRT? wdyt @lino-levan
