### ISSUE TITLE
Add support for footnotes

### ISSUE THREAD

**Issue by bkircher** [denoland/deno-gfm#6]
Have been added last year https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/

**Comment by bkircher** [comment]
Ah, sorry. Wrong repo, I guess. https://github.com/markedjs/marked/issues/714. Should have looked first

**Comment by hashrock** [comment]
If it is not the responsibility of the parser(marked), perhaps it should be implemented here.

**Comment by lino-levan** [comment]
I think we should probably give it our best shot knowing that it won't be perfectly the same as GitHub (as with math rendering). We can fix bugs as they arise. I'll play around with footers and maybe make a PR if I have time.
