### ISSUE TITLE
/x does not render text as bold if followed by a hard line-break

### ISSUE THREAD

**Issue by clo4** [denoland/deno-gfm#68]
It's entirely possible this bug is upstream.

### The markup

```markdown
- **Breaking: Changed how clients are instantiated with an API (#0)**\
  The API object must now be passed in as an api property on an object.
```

### How GitHub renders it

- **Breaking: Changed how clients are instantiated with an API (#0)**\
  The API object must now be passed in as an api property on an object.

### And on deno.land/x

![image](https://user-images.githubusercontent.com/52195359/134476801-413e87fe-caa1-43da-a18c-30a52baed76c.png)
---

Interestingly it seems to only affect lines that end with a non-alphanumeric character, but I haven't tested further.
![image](https://user-images.githubusercontent.com/52195359/134492233-1af91e2c-5c7e-4a61-8d61-32f29a0b998c.png)

**Comment by lino-levan** [comment]
@hashrock does remark handle this case better?

**Comment by hashrock** [comment]
Yes it does

**Comment by deer** [comment]
@hashrock, I think this can be closed. When I go to https://deno.land/x/jamf_school@0.2.0/README.tpl.md?source=#version-020, I see the problematic text now rendered correctly.

**Comment by clo4** [comment]
Agreed. It’s been a while since I had this problem, to be honest I forgot this issue was still open in the first place!
