### ISSUE TITLE
HTML appears in code

### ISSUE THREAD

**Issue by dsherret** [denoland/deno-gfm#69]
https://deno.land/x/dax@0.32.0#output-a-command-before-executing-it

![image](https://github.com/denoland/doc_components/assets/1609021/4f6f75d5-15a5-408e-958c-1c4d569c6e63)

Expected:

![image](https://github.com/denoland/doc_components/assets/1609021/fdccb690-5c9e-4ad6-8510-76ff0e2fbb2b)

**Comment by kt3k** [comment]
I think we shouldn't perform math expression transformation to the entire input https://github.com/denoland/deno-gfm/blob/8a3481e8ee962fdb182e7feb07fa575110764b71/mod.ts#L101

**Comment by lino-levan** [comment]
We definitely need to switch to `remark-gfm` instead of just hacking math / emoji support into `marked`.
