### ISSUE TITLE
Dependency Deprecation Warning

### ISSUE THREAD

**Issue by roberto-morado** [denoland/deno-gfm#70]
Hello there! 👋

I noticed a deprecation warning in the module's dependency, `marked()`. The warning states that the `mangle` parameter is deprecated since version 5.0.0 and should not be used. Instead, it recommends using the npm package `marked-mangle`.

I kindly request the maintainers to consider updating the dependency, as suggested in the deprecation warning. This change will ensure the continued compatibility and stability of the module for Deno users.

### Warning

> marked(): mangle parameter is deprecated since version 5.0.0, should not be used and will be removed in the future. Instead use https://www.npmjs.com/package/marked-mangle.

**Comment by lino-levan** [comment]
I'll open a PR. Sorry for the trouble.
