### ISSUE TITLE
Support "Note" and "Warning" highlight like GitHub

### ISSUE THREAD

**Issue by o-az** [denoland/deno-gfm#75]
https://github.com/orgs/community/discussions/16925#discussion-4085374

Are there plans to support this:

![CleanShot 2023-07-31 at 18 39 43@2x](https://github.com/denoland/deno-gfm/assets/23618431/dec1b1d6-6f12-4936-9dd7-c6f2277bbf74)

**Comment by kitsonk** [comment]
It is "in production" now on GitHub. Would be great to get the support. Might take a look at it if I find the time.
